config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }  
  root 'home#top'
  resources :home, :only => [:new, :create]
  resources :users, :only => [:show, :index]
  resources :comments, :only => [:create, :destroy]
  resources :genres
  resources :materials
  get 'rooms/related' => "rooms#related"
  resources :rooms, :only => [:create, :show, :index]
  resources :messages
  resources :users do
        member do
         get :following, :followers
        end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :inquiries, :only => [:new, :create, :index] do
    resources :answers
  end
#   resources :likes, :only => [:create, :destroy]
  post "likes/:recipe_id/create" => "likes#create"
  post "likes/:recipe_id/destroy" => "likes#destroy"
  get "users/:id/likes" => "users#likes"
  resources :recipes do
        collection do 
          post :recipe_search
          get :genre_search
          get :vegetable
          get :meat
          get :fish
          get :rice
          get :pasta_gratin
          get :noodles
          get :soup
          get :salad
          get :powder
          get :other
        end
  end
  resources :recipes do
    resources :comments
  end
  # post "/recipes/genre_search" => "recipes#genre_search"
  # get 'recipes/recipe_search' => 'recipes#recipe_search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
         
  # バリデーション
  validates :nickname, presence: true
         
  has_many :messages, inverse_of: 'sender'
  has_many :entries, :dependent => :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :recipes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  mount_uploader :image, ImagesUploader
  
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :prefecture, :gender])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :image, :prefecture, :gender, :introduction, :email])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    edit_user_registration_path
  end
  
  def after_update_path_for(resource)
      users_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  # def after_sign_in_path_for(resource)
  #   if (session[:previous_url] == root_path)
  #     super
  #   else
  #     session[:previous_url] || root_path
  #   end
  # end
  
  
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:index, :show, :following, :followers, :likes] 
  
  def show
    @user = User.find_by(id: params[:id])
    @recipes = Recipe.where(user_id: @user.id).order(created_at: :desc)
    currentUserEntry = Entry.where(user_id: current_user.id).pluck(:room_id)
    userEntry = Entry.where(user_id: @user.id).pluck(:room_id)
    currentUserRoomId = currentUserEntry & userEntry
    if currentUserRoomId.present?
      @roomId = currentUserRoomId[0]
      @isRoom = true
    else
      @room = Room.new
      @entry = Entry.new
    end
  end

  def index
    @users = User.where.not(id: current_user).paginate(page: params[:page], per_page: 10)
  end
  
  def following
    @user = User.find_by(id: params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find_by(id: params[:id])
    @users = @user.followers
    render 'show_follower'
  end
  
  def likes
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id).order(created_at: :desc)
    currentUserEntry = Entry.where(user_id: current_user.id).pluck(:room_id)
    userEntry = Entry.where(user_id: @user.id).pluck(:room_id)
    currentUserRoomId = currentUserEntry & userEntry
    if currentUserRoomId.present?
      @roomId = currentUserRoomId[0]
      @isRoom = true
    else
      @room = Room.new
      @entry = Entry.new
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
     user == current_user
    end
    
    def prefecture_name(id)
        if id.present?
            Prefecture.find_by(id: id).name
        else
            "設定されていません"
        end
    end
    
    def gender_name(gender)
        if gender.present?
            case gender
            when "m"
              "男性"
            when "f"
              "女性"
            when "o"
              "その他"
            else
              "性別が設定されていません"
            end
        else
            "性別が設定されていません"
        end
    end

    def following_check(user_id)
      users = User.where(id: current_user.followings & current_user.followers).pluck(:id)
      users.include?(user_id)
    end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "follow_btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/users/_unfollow.html.erb
<button class="unfollow_btn", id="following_delete_btn">フォローを解除する</button>
    <div id="follow_bg">
        <div id="following_delete_alertbox">
            <p>本当にフォローを解除しますか？</p>
            <button id="follow_close_btn">いいえ</button>
            <div class="unfollow_div">
                <%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
                  <%= f.submit "はい", :id => "follow_delete" %>
                <% end %>
            </div>
        </div>
    </div>

app/views/users/index.html.erb
<div class="container">
  <h1>ユーザー一覧</h1>
  <div class="user_index">
    <% @users.each do |user| %>
      <div class="user_index_clear">
        <% if user.image.present? %>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.image %>
          <% end %>
        <% else %>
          <%= link_to user_path(user.id) do %>
            <i class="fas fa-user-circle fa-4x fa-fw my-skyblue"></i>
          <% end %>
        <% end %>
        <%= link_to user.nickname, user_path(user.id), class: "user_index_username" %>
      </div>
    <% end %>
  </div>
  <%= will_paginate @users, previous_label: '<', next_label: '>', inner_window: 1, outer_window: 0 %>
</div>

app/views/users/likes.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <div class="user-info">
        <% if @user.image.present? %>
          <%= image_tag @user.image %>
        <% else %>
          <i class="fas fa-user-circle fa-7x fa-fw my-skyblue"></i>
        <% end %>
        <h2><%= @user.nickname %></h2>
        <p><%= @user.introduction %></p>
        <p><i class="fas fa-map-marker-alt fa-fw"></i><%= prefecture_name(@user.prefecture) %></p>
        <p><%= gender_name(@user.gender) %></p>
        <% if @user.id == current_user.id %>
          <span class="to_user_edit"><%= link_to("ユーザー情報の編集", "/users/edit") %></span>
        <% end %>
      </div>

      <% if @user.id != current_user.id %>
        <div class="message_create">
          <% if following_check(@user.id) %>
            <% if @isRoom %>
              <p><a href="/rooms/<%= @roomId %>", class="user_show_to_room_btn">チャットへ</a>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, :value => @user.id %>
                <% end %>
                <%= f.submit "チャットを始める", :class => "user_show_room_new_btn" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%= render 'follow_form' %>
      <br>
      <%= render 'stats' %>
    </div>
  
    <ul class="user-tabs">
      <li><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li class="active"><%= link_to("お気に入り", "/users/#{@user.id}/likes") %></li>
    </ul>
    <div class="likes_recipe_wrapper">
      <% if @likes.present? %>
        <% @likes.each do |like| %>
          <% recipe = Recipe.find_by(id: like.recipe_id) %>
          <div class="recipes-index-item" id="wrap">
            <div class="recipe_index">
                <% if recipe.image.present? %>
                    <div class="image_container">
                        <%= image_tag recipe.image %>
                    </div>
                <% else %>
                    <div class="no_image_container">
                        <p>No Image</p>
                    </div>
                <% end %>
                <%= link_to recipe.name, recipe_path(recipe.id) %><br>
                <%= link_to(recipe.user.nickname, "/users/#{recipe.user.id}") %>
                <i class="fas fa-heart heart-red"></i>
                <%= Like.where(recipe_id: recipe.id).count %><br>
                <% msg = '材料:'%>
                <%= msg %>
                <%= recipe.materials %>
                <% if recipe.tag_list.present? %>
                    <div class="recipe_show_tag">
                        <i class="fas fa-tags fa-fw"></i>
                        <% recipe.tag_list.each do |tag| %>
                          <%= link_to tag, recipes_path(tag_name: tag), :class => "show_tag_container" %>
                        <% end %>
                    </div>
                <% end %>
                <div class="recipe_updated_at">
                    <%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %>
                </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>お気に入りはありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <div class="user-info">
        <% if @user.image.present? %>
          <%= image_tag @user.image %>
        <% else %>
          <i class="fas fa-user-circle fa-7x fa-fw my-skyblue"></i>
        <% end %>
        <h2><%= @user.nickname %></h2>
        <p><%= @user.introduction %></p>
        <p><i class="fas fa-map-marker-alt fa-fw"></i><%= prefecture_name(@user.prefecture) %></p>
        <p><%= gender_name(@user.gender) %></p>
        <% if @user.id == current_user.id %>
          <span class="to_user_edit"><%= link_to("ユーザー情報の編集", "/users/edit") %></span>
        <% end %>
      </div>
      <% if @user.id != current_user.id %>
        <div class="message_create">
          <% if following_check(@user.id) %>
            <% if @isRoom %>
              <p><a href="/rooms/<%= @roomId %>", class="user_show_to_room_btn">チャットへ</a>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |e| %>
                  <%= e.hidden_field :user_id, :value => @user.id %>
                <% end %>
                <%= f.submit "チャットを始める", :class => "user_show_room_new_btn" %>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <%= render 'follow_form' %>
      <br>
      <%= render 'stats' %>
    </div>
    
    <ul class="user-tabs">
      <li class="active"><%= link_to("投稿", "/users/#{@user.id}") %></li>
      <li><%= link_to("お気に入り", "/users/#{@user.id}/likes") %></li>
    </ul>
    <div class="index_recipe_wrapper">
      <% if @recipes.present? %>
        <% @recipes.each do |recipe| %>
          <div class="recipes-index-item" id="wrap">
            <div class="recipe_index">
                <% if recipe.image.present? %>
                    <div class="image_container">
                        <%= image_tag recipe.image %>
                    </div>
                <% else %>
                    <div class="no_image_container">
                        <p>No Image</p>
                    </div>
                <% end %>
                <%= link_to recipe.name, recipe_path(recipe.id) %><br>
                <%= link_to(recipe.user.nickname, "/users/#{recipe.user.id}") %>
                <i class="fas fa-heart heart-red"></i>
                <%= Like.where(recipe_id: recipe.id).count %><br>
                <% msg = '材料:'%>
                <%= msg %>
                <%= recipe.materials %>
                <% if recipe.tag_list.present? %>
                    <div class="recipe_show_tag">
                        <i class="fas fa-tags fa-fw"></i>
                        <% recipe.tag_list.each do |tag| %>
                          <%= link_to tag, recipes_path(tag_name: tag), :class => "show_tag_container" %>
                        <% end %>
                    </div>
                <% end %>
                <div class="recipe_updated_at">
                    <%= recipe.updated_at.strftime("%Y-%m-%d %H:%M") %>
                </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>投稿はありません</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="container">
  <h1>フォロー一覧</h1>
  <div class="user_index">
    <% if @users.present? %>
      <% @users.each do |user| %>
        <div class="user_index_clear">
          <% if user.image.present? %>
            <%= link_to user_path(user.id) do %>
              <%= image_tag user.image %>
            <% end %>
          <% else %>
            <%= link_to user_path(user.id) do %>
              <i class="fas fa-user-circle fa-4x fa-fw my-skyblue"></i>
            <% end %>
          <% end %>
          <%= link_to user.nickname, user_path(user.id), class: "user_index_username" %>
        </div>
      <% end %>
    <% else %>
      <p>フォローしているユーザーがいません</p>
    <% end %>
  </div>
</div>

app/views/users/show_follower.html.erb
<div class="container">
  <h1>フォロワー一覧</h1>
  <div class="user_index">
    <% if @users.present? %>
      <% @users.each do |user| %>
        <div class="user_index_clear">
          <% if user.image.present? %>
            <%= link_to user_path(user.id) do %>
              <%= image_tag user.image %>
            <% end %>
          <% else %>
            <%= link_to user_path(user.id) do %>
              <i class="fas fa-user-circle fa-4x fa-fw my-skyblue"></i>
            <% end %>
          <% end %>
          <%= link_to user.nickname, user_path(user.id), class: "user_index_username" %>
        </div>
      <% end %>
    <% else %>
      <p>フォロワーがいません</p>
    <% end %>
  </div>
</div>