config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }  
  root 'home#top'
  resources :home, :only => [:new, :create]
  resources :users, :only => [:show, :index]
  resources :comments, :only => [:create, :destroy]
  resources :genres
  resources :materials
  get 'rooms/related' => "rooms#related"
  resources :rooms, :only => [:create, :show, :index]
  resources :messages
  resources :users do
        member do
         get :following, :followers
        end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :inquiries, :only => [:new, :create, :index] do
    resources :answers
  end
#   resources :likes, :only => [:create, :destroy]
  post "likes/:recipe_id/create" => "likes#create"
  post "likes/:recipe_id/destroy" => "likes#destroy"
  get "users/:id/likes" => "users#likes"
  resources :recipes do
        collection do 
          post :recipe_search
          get :genre_search
          get :vegetable
          get :meat
          get :fish
          get :rice
          get :pasta_gratin
          get :noodles
          get :soup
          get :salad
          get :powder
          get :other
        end
  end
  resources :recipes do
    resources :comments
  end
  # post "/recipes/genre_search" => "recipes#genre_search"
  # get 'recipes/recipe_search' => 'recipes#recipe_search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
    has_many :entries
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, :only => [:create, :show, :index, :related]


  def related
    @users = User.where(id: current_user.followings & current_user.followers)
    @current_user_entries = Entry.where(user_id: current_user.id)
    @entries = []
    @user_is_rooms = {}
    @users.each do |user|
      @is_room = false
      @user_entries = Entry.where(user_id: user.id)
      @current_user_entries.each do |cu|
        @user_entries.each do |u|
          if cu.room_id == u.room_id then
            @is_room = true
            @user_is_rooms[user.id] = true
            @entries.push(u)
          end
        end
      end
      if @is_room == false
        @user_is_rooms[user.id] = false
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
    # flash[:notice] = "チャットを作成しました！"
  end

  def show
    @room = Room.find_by(id: params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
      flash[:alert] = "無効なユーザーです"
    end
    @current_entries = current_user.entries
    @another_entries = Entry.where(room_id: @room.id).where('user_id != ?', current_user.id)
  end

  def index
    @current_entries = current_user.entries
    my_room_ids = []
    @current_entries.each do |entry|
      my_room_ids << entry.room.id
    end
    @another_entries = Entry.where(room_id: my_room_ids).where('user_id != ?', current_user.id)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h2>チャット情報を編集する</h2>
<hr>
<%= form_for @room do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control my-form", :placeholder => "名前を入力して下さい" %>
  <br>
  <%= f.label :explain %>
  <%= f.text_area :explain, :class => "form-control my-form", :size => "30x10", :placeholder => "説明を入力して下さい" %>
  <br>
  <%= f.submit "変更する", :class => "btn btn-success" %>
<% end %>
<hr>
<p><a href="/rooms/<%= @room.id %>" class="btn btn-primary">チャット情報に戻る</a></p>
<p><a href="/" class="btn btn-info">トップに戻る</a></p>

app/views/rooms/index.html.erb
<div class="container">
  <h1>チャット一覧</h1>
  <div class="room_index_container">
    <span class="to_room_related"><%= link_to("相互フォロー一覧", "/rooms/related") %></span>
    <div class="room_index_wrapper">
      <% if @another_entries.present? %>
        <% @another_entries.each do |e| %>
          <div class="room_index">
            <% if e.user.image.present? %>
              <%= link_to room_path(e.room_id) do %>
                <%= image_tag e.user.image %>
              <% end %>
            <% else %>
              <%= link_to room_path(e.room_id) do %>
                <i class="fas fa-user-circle fa-4x fa-fw my-skyblue"></i>
              <% end %>
            <% end %>
            <%= link_to room_path(e.room_id), class: "room_index_username" do %>
              <%= e.user.nickname %>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <span class="non_room"><p>チャットがありません</p></span>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/related.html.erb
<div class="container">
  <h1>相互フォロー一覧</h1>
  <% if @users.present? %>
    <% @users.each do |user| %>
      <div class="room_related">
        <% if user.image.present? %>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.image %>
          <% end %>
        <% else %>
          <%= link_to user_path(user.id) do %>
            <i class="fas fa-user-circle fa-4x fa-fw my-skyblue"></i>
          <% end %>
        <% end %>
          <%= link_to(user.nickname, "/users/#{user.id}", :class => "related_name") %>
        <% if @user_is_rooms[user.id] == true %>
          <% @entries.each do |entry| %>
             <% if entry.user_id == user.id %>
              <a href="/rooms/<%= entry.room_id %>" class="to_show_related_btn">チャットへ</a>
             <% end %>
          <% end %>
        <% else %>
          <%= form_for @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, :value => user.id %>
            <% end %>
            <%= f.submit "チャットを始める", :class => "room_new_btn" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <span class="non_related"><p>相互フォロワーがいません</p></span>
  <% end %>
</div>

app/views/rooms/show.html.erb
<br>
<div class="row">
  <div class="container-message">
    <div class="room_show_text-center">
      <% @another_entries.each do |e| %>
        <p><%= e.user.nickname %></p>
      <% end %>
    </div>
  <div class="line-bc" id="line-bc">
    <% if @messages.present? %>
      <% @messages.each do |m| %>
        <% if m.sender_id == current_user.id %>
          <div class="mycomment">
            <p><%= m.message %></p>
          </div>
          <div class="bms_clear"></div>
        <% else %>
          <div class="balloon6">
            <div class="faceicon">
              <i class="fas fa-user-circle fa-2x fa-fw my-skyblue"></i>
            </div>
            <div class="chatting">
              <div class="says">
                <p><%= m.message %></p>
              </div>
            </div>
          </div>
          <div class="bms_clear"></div>
        <% end %>
      <% end %>
    <% else %>
      <br>
      <h3 class="text-center">メッセージはまだありません</h3>
      <br>
    <% end %>
    </div>
    <br>
    <div id="bms_send">
      <%= form_for @message do |f| %>
        <%= f.text_field :message, :id => "bms_send_message", :placeholder => "メッセージを入力して下さい" %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <%= f.submit "送信", :id => "bms_send_btn" %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).on('turbolinks:load', function() {
    var obj;
    obj = document.getElementById('line-bc');
    obj.scrollTop = obj.scrollHeight;
  });
</script>