config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   :sessions => 'users/sessions'
  }  
  root 'home#top'
  resources :home, :only => [:new, :create]
  resources :users, :only => [:show, :index]
  resources :comments, :only => [:create, :destroy]
  resources :genres
  resources :materials
  get 'rooms/related' => "rooms#related"
  resources :rooms, :only => [:create, :show, :index]
  resources :messages
  resources :users do
        member do
         get :following, :followers
        end
  end
  resources :relationships, :only => [:create, :destroy]
  resources :inquiries, :only => [:new, :create, :index] do
    resources :answers
  end
#   resources :likes, :only => [:create, :destroy]
  post "likes/:recipe_id/create" => "likes#create"
  post "likes/:recipe_id/destroy" => "likes#destroy"
  get "users/:id/likes" => "users#likes"
  resources :recipes do
        collection do 
          post :recipe_search
          get :genre_search
          get :vegetable
          get :meat
          get :fish
          get :rice
          get :pasta_gratin
          get :noodles
          get :soup
          get :salad
          get :powder
          get :other
        end
  end
  resources :recipes do
    resources :comments
  end
  # post "/recipes/genre_search" => "recipes#genre_search"
  # get 'recipes/recipe_search' => 'recipes#recipe_search'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    
    # if user && user.admin?
    #   can :access, :rails_admin   
    #   can :manage, :all           
    # end 
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :inquiry
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :recipe
    validates :content, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :room
    belongs_to :user
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
    mount_uploader :image, ImagesUploader
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    has_many :answers, :dependent => :destroy
end

app/models/like.rb
class Like < ApplicationRecord
    validates :user_id, {presence: true}
    validates :recipe_id, {presence: true}
    belongs_to :user
    belongs_to :recipe
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: 'user_id'
    belongs_to :room
    
    def user
        return User.find_by(id: self.sender_id)
    end
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    acts_as_taggable
    belongs_to :user
    has_many :likes, :dependent => :destroy
    has_many :comments, :dependent => :destroy
    mount_uploader :image, ImagesUploader
    
    def user
        return User.find_by(id: self.user_id)
    end
    
    def self.search(search)
      if search
        Recipe.where('name LIKE ?', "%#{search}%")
      else
        Recipe.all
      end
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
    has_many :entries
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
         
         
  # バリデーション
  validates :nickname, presence: true
         
  has_many :messages, inverse_of: 'sender'
  has_many :entries, :dependent => :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :recipes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy
  mount_uploader :image, ImagesUploader
  
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
    
    before_action :authenticate_user!, only: [:index]
    before_action :user_admin, only: [:index]
    
    def index
        @inquiries = Inquiry.all.order(created_at: :desc)
    end
    
    def new
        @inquiry = Inquiry.new
    end
    
    def create
        @inquiry = Inquiry.new(inquiry_params) 
        respond_to do |format|
            if @inquiry.save
                InquiryMailer.send_when_create(@inquiry).deliver
                InquiryMailer.send_to_owner(@inquiry).deliver
                format.html { redirect_to "/", notice: 'お問い合わせを受け付けました' }
                format.json { render :show, status: :created, location: @inquiry }
            else
                format.html { render :new }
                format.json { render json: @inquiry.errors, status: :unprocessable_entity }
            end
        end
    end
    
    private
    
        def inquiry_params
            params.require(:inquiry).permit(:name, :email, :content)
        end
        
        def user_admin
          @users = User.all
          if  current_user.admin == false
              redirect_to recipes_path
          end
        end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
     user == current_user
    end
    
    def prefecture_name(id)
        if id.present?
            Prefecture.find_by(id: id).name
        else
            "設定されていません"
        end
    end
    
    def gender_name(gender)
        if gender.present?
            case gender
            when "m"
              "男性"
            when "f"
              "女性"
            when "o"
              "その他"
            else
              "性別が設定されていません"
            end
        else
            "性別が設定されていません"
        end
    end

    def following_check(user_id)
      users = User.where(id: current_user.followings & current_user.followers).pluck(:id)
      users.include?(user_id)
    end
end

app/views/inquiries/index.html.erb
<div class="inquiries_container">
    <h1>お問い合わせ一覧</h1>
    <table border="1">
        <tr>
            <th>名前</th>
            <th class="inquiries_mail">メールアドレス</th>
            <th>内容</th>
            <th>回答</th>
        </tr>
    <% if @inquiries.present? %>
        <% @inquiries.each do |inquiry| %>
            <tr class="inquiry_tr">
                <td class="inquiries_name"><%=inquiry.name %></td>
                <td class="inquiries_mail"><%=inquiry.email %></td>
                <td class="inquiries_content">
                    <p class="inquiry_content"><%=link_to inquiry.content, new_inquiry_answer_path(inquiry.id) %></p>
                    <p class="inquiry_create_at"><%= inquiry.created_at.strftime("%Y-%m-%d %H:%M") %></p>
                </td>
                <td class="inquiries_answer">
                    <% @answers = Answer.where(inquiry_id: inquiry.id) %>
                    <% if @answers.present? %>
                      <% @answers.each do |answer| %>
                        <p class="answer_content"><%= answer.content %></p>
                        <p class="answer_create_at"><%= answer.created_at.strftime("%Y-%m-%d %H:%M") %></p>
                        <br>
                      <% end %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    <% end %>
    </table>
</div>

app/views/inquiries/new.html.erb
<div class="container">
    <h1>お問い合わせフォーム</h1>
    <%= form_for @inquiry do |f| %>
        <div class="field">
          <%= f.label '名前', :class => "form_name" %>
          <%= f.text_field :name, class: 'form-control', required: true %>
        </div>
        
        <div class="field">
          <%= f.label 'メールアドレス', :class => "form_name" %>
          <%= f.text_field :email, class: 'form-control', required: true %>
        </div>
        
        <div class="field">
          <%= f.label "内容", :class => "form_name" %>
          <%= f.text_area :content, class: 'form-control-area', required: true %>
        </div> 
        
        <div class="actions inquiry_div">
          <%= f.submit "送信", class: "inquiry_btn" %>
        </div>
    
    <% end %>
</div>